### PR TITLE
Move Fahrinfo Dresden to EFA section

### PR DESCRIPTION
**Pull request by kiliankoe**
pretty sure this one is EFA based

### CODE REVIEW

**Comment by derhuerst** [comment]
thanks!

**Comment by kiliankoe** [comment]
btw, is it EFA or EVA? Or is that something completely different?

**Comment by derhuerst** [comment]
No idea to be honest, but would also be interested in an answer on that. @ubahnverleih do you know?

**Comment by kiliankoe** [comment]
Looks to be [EFA](https://de.wikipedia.org/wiki/Elektronische_Fahrplanauskunft_(Software)), for *Elektronische Fahrplanauskunft*.

**Comment by juliuste** [comment]
I just had another look at [the app](https://itunes.apple.com/app/id314790387), and it's actually neither HAFAS nor EFA, but FIFFI. (\**sigh*\* those names… 😄)

Fixed it for `next` in [`f7e56d4`](https://github.com/public-transport/public-transport-apps-encryption/commit/2dd3bf564cd0e533152de6e712ff022d8870bdc5)

**Comment by kiliankoe** [comment]
Oh wow, you're right. That's definitely new.

**Comment by kiliankoe** [comment]
Regarding your commit, Fahrinfo Dresden is not the official DVB application. That would be [this one](https://itunes.apple.com/de/app/dvb-mobil/id1174905421?l=en), which uses a different [endpoint](https://github.com/kiliankoe/vvo/blob/master/documentation/webapi.md). I'm not sure though if that's something custom or also used elsewhere.

**Comment by juliuste** [comment]
> Regarding your commit, Fahrinfo Dresden is not the official DVB application. That would be this one, which uses a different endpoint. I'm not sure though if that's something custom or also used elsewhere.

Good point, I should add documentation for the attributes in `list.json` on the `next` branch.

`agency` just roughly describes which area an app covers without necessarily having to be **the** application for a specific public transport authority. This is why there's also the `official` attribute which is `false` for `FahrInfo Dresden`.

We did this to allow people to compare multiple applications (both official and inofficial) for their local provider so that they could see if there was another app available for them, e.g. with better security, if that makes sense. The format that I've come up with is probably not the best, though, so please let me know if anything else doesn't add up from your point of view.

We should also have a look at the official app you mentioned, and add it to the list, I can do that in the next few days 🙂 [*edit*] if you dont already know if the official app is using HTTPS / key pinning / etc. 😄 [*/edit*]

**Comment by derhuerst** [comment]
FYI there were quite a few using *fiffi* when we checked last time. It's definitely not a unique thing.

**Comment by kiliankoe** [comment]
> if you dont already know if the official app is using HTTPS / key pinning / etc.

I know for sure that it doesn't pin any keys. It also sends requests TLS secured by default, but the api doesn't redirect to the HTTPS version.

**Pull request merged**
